apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv
spec:
  capacity:
    storage: 1Gi          # Size of the volume
  accessModes:
    - ReadWriteOnce       # Can be mounted read/write by one node
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mosquitto-data  # Path on the node
