
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJY0dLSzFpRno4OEl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1qZ3hORE01TVRsYUZ3MHpOakF4TWpZeE5EUTBNVGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM0Wi9vdmVNa1pxQS93SFU2blo4dkNGNDNBVEt2anJ2UTkzRHBuKzVhR1BqYlIwT0k3WDYzZWRhcmYKSm55L1BNSVQyaENoaGJrRjhxSjZNWG13UFA2bGpjR0ZjdmQya3VkNzBsbkRkZ2d1OFJ1UFFnR2JTbUxyaFNJWQo0ZUMvbUFCNGp0bU01VmFucHFKTktFMVBycU81QlRMS0RpaGhaQXBtR2NUQnVQVHJndG5OdnJPNE1hZjRmZlpoCk5OV0NBUnUvYUljY0lzVG90WFZINVRYRXB5QVRKWkJHY2hLOVlBQlJqQlo5QnA2UkJkSzVpK3BqRk5FT2NXbDEKOXczTEl1d0lHSkdMaG5aM2lxZEpqclAvM25pd3VoMm9xWHRRWjhtUC9SL0ZpVUtGaDk3c2RJUXpuaFZFbXhaNQpDTDY0WG9kZVArQVRrUnVJYmtBUW1DbmJPZzY1QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRU2ZIYTFaSlRkRFZxM1FLcVcyUEc0Y042dkJqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjlyN3ZoN0FPUQpTb0VRNFJndkY1VTV6VDNDMDR4NVh1TGZrWWtQamhKandvbFgrUWgyZithVzZoOGhSSEFiYmc5a3pDVnlsS3lvCnkvUis2YklHSkxuK3VsbnRNLzY1c0U0R0RrWGxCSlpoSmZ5aGJXVkNSam4wMmtHM1lQc3B2cHhEMlFrQ3drWG0KanVGVTZvSms3QnJBajZCaE9tOVM5aGFBRWl6aWdwUzdmQWY5NUExMXlUVWhJSFBEbXlIR0NmWWZxVkM1cG44dwp4VGZYU09PSVhhbVl0eXkyckNFY1ZJSmc0ejNSRU5xRUw0SFB5Sm1HQ01KZXhyNndHUnVoVHdPcjhDMUU0bG14CkdiNzFBN20xdHlHVzhOaHQ3bHNSeldmeU15RkwzSXZEenlDV3h5NjFERDZKSkxpL2p1TkxmdEl0RzYycmJLL0wKeno0K0MxU0ZnQmZTCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://ceb963c7-3b53-4ffb-9441-7028c7ac2f0b.fr-par-2-gw.linodelke.net:443
  name: lke562252

users:
- name: lke562252-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImFhU1oyQ3hnekd0dFF4UGJPTnRTRXJKdDdsbXVCUzdwYm90RzlwdDFqNU0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tNXhkNjYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZTNhZjBlMWEtYmJiYy00YWY3LThjZjctNjYxYmQ2MTQ4Y2RmIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.Akj06WVrZ6Qn2Pyu3bEoMH-oDRzshPpGvt3Zuu4pmcB9Q_2eWzLX88-aK3E6D7u4jXAqZ2WD229m522MlFIPQUnjK0Ca9t1AKxaVOrdSGdFzdQ1iCGH8oTGpFi1kS4JShg5GfijwLDotNTgd0XOydDyOrkKw-cwSvMFKMOIijfQaYYE6XrO5n7f_P-zqcFC_samdZ2kVq_MhJZ7jcf4jzxAM6smN36qziK7fS0SPeTS-vv6WXjTflpqs6qo3KUTsqQQlmSY7K_klZ2ge9PgeWQkj_dlO756Dba2H_TSmv8EQ00eTmGAQyEb00UA87PiDAZS3VrVMt_qna6eBHoiDrg

contexts:
- context:
    cluster: lke562252
    namespace: default
    user: lke562252-admin
  name: lke562252-ctx

current-context: lke562252-ctx
