
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJV0xoK05SbzY3OVV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1qZ3hPVFV5TlROYUZ3MHpOakF4TWpZeE9UVTNOVE5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMzK3M1UFhQYjYrRC8xSjI1L0JUeVJzeEtINkhTdVhkZUh3T0Vwb0dxU3NJY1pESGtmdVZPNFF6VFYKbVJMVmdiMlBpRXZRYUFkUy9ocmhGVFVCbXVCNTZ5alh4UE1EQzdTU01jRHdNdkF5VGpuOXVVWnUrQzZjUXVBbgp3N1hMV2tKaUZRSUJUZVhoVG5XY0pFZyszSnY2YVNZZ0VCVElrQzAyaVVtRi9ESWdPMkpRN0NWWU1iYkdIRStUCjNsUnVXb0F5L3R5MEE1Q1ZCN1ZGaHpYajVjMWx6NEhjNmhLNk43WHNGdmRGdnh1c0dMZ2pVV2lRV01xMzh6QkYKLysyVFJFdGowRjNmQkhZYzcvcy82d3AzRUhQalQrcllHSmJBVDZ5L00wZXVZdUZVKzc2cFVnQXh2bmZvdG14bQpKZVlYRiszUTFieWR6QTU1cDUyckhVa25vTTFGQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUd2xkREFOcnMyRm1NWFcrQlFtS29ENEgzVENUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkp5K1dWSlVXOApSWWlaaUNBY2tyT3NsZG5qQkZRR3pReHBRQjNnbE9oL3E3N2lyaTdXc2J4d1N2QTUrdDNQU2FMN3BjbTVRejJoCmpUUWlrSXYvM1FtZE9WTHJGMmN4VzF6YlErSXZkSWQxZEdZWm5FOTE2MXd6ZGEycVBPcFp4akgwdzRoNC8xOVgKMmlhTmZzY3EwS3ZuQmROc1NYeGVYZXplTW9iZGtDM1RmbEhvSXlJc1IvN1VKUDBBclRaWU1sODJtVkpxcnE2TAplWWR1STdsN3M2M2ZjMUN0TS9kUkJYTVEwT09aY1MzQmx5VHB4aU9FckFXamxsNERKMUl0WmJuUVcvSFdyQVFkCllMc0RmS0d1NGV4dHAwVHdxRVZpcHl1ZEdMc1RQbmhleU40TFZ5aXEyNkNMcGFoaFVxZk5uOXY1SDRPa1pzYk0KNDFZZy90ZGZZWk1pCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://702d1b16-8072-4d43-9e0a-503b89a14692.fr-par-1-gw.linodelke.net:443
  name: lke562388

users:
- name: lke562388-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJzSDgxdlVjRDJVWEprRmE0N2Z5eldTbkVBdVlXVWd4YVZvTldPbklxNEUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tYjQ5dHIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMjI1MDQzNGUtYTA0Yi00ZTI2LWJmZWItMzYxNDI4ZmY4Yzk2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.4P_P42bXdgQWJyr0v_LcrYHYnVwGTmLpYo-tuxlhK4hWMKhTeZfutj2YK_1OJS-fOXnLF2HoZMTP2Rw-v6Y8fBW4DU3dTtNINlaHSfBZfAXTqmNOALtl5oTelgpRmghUv7B6Tt5vE54piKHB0V3sb6L56_DtleZ2NqttkdLuU_mZwoBNQpX2EUCg-HuSBCmZ5F7jPg2WjFNgUfwrQvK8uYIEhksq0ev4yvvfDs7nqmJLHBPldO2arCo-7ohtk8U5YzvlBGc1z8dWTgCiH2sd7yd4207aTVI9ZKF7XziHQ6_g9G-6vulB5W1NZP5XFgL62QbMFsuIeHGaYpqdjvciIg

contexts:
- context:
    cluster: lke562388
    namespace: default
    user: lke562388-admin
  name: lke562388-ctx

current-context: lke562388-ctx
